apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30080  # Choisissez un port dans la plage autorisée (par défaut 30000-32767) pour HTTP.
    - name: "https"
      port: 443
      targetPort: 443
      nodePort: 30443  # Choisissez un port dans la plage autorisée (par défaut 30000-32767) pour HTTPS.
  selector:
    app: nginx  # Assurez-vous que ce label correspond aux labels de vos pods nginx.
